import { StyleSheet } from "react-native";
import { Colors } from "@/constants/colors";

export const panelStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.cream },
  header: {
    backgroundColor: Colors.card,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
    paddingHorizontal: 16,
    paddingBottom: 0,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    height: 44,
  },
  headerDivider: {
    height: 1,
    backgroundColor: Colors.border,
    marginHorizontal: -16,
  },
  headerLeftActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  backBtn: { 
    width: 40, 
    height: 40, 
    alignItems: "center", 
    justifyContent: "center",
  },
  adminCircleBtn: {
    width: 40, 
    height: 40, 
    alignItems: "center", 
    justifyContent: "center",
  },
  adminCircleText: {
    fontSize: 17,
    fontFamily: "Montserrat_600SemiBold",
    color: Colors.green,
  },
  headerTitle: {
    fontSize: 16,
    fontFamily: "Montserrat_400Regular",
    color: Colors.darkOrange,
    flex: 1,
    marginLeft: 8,
  },
  publishBtn: {
    backgroundColor: Colors.maroon,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    minWidth: 110,
    alignItems: "center",
  },
  publishBtnSuccess: { backgroundColor: Colors.green },
  publishBtnText: { fontSize: 13, fontFamily: "Montserrat_400Regular", color: "#fff" },
  tabsRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 4,
  },
  addSectionTabBtn: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 4,
  },
  tabsScroll: { flex: 1, flexGrow: 1 },
  tabsContent: { paddingRight: 16, gap: 0 },
  tabBtn: { paddingVertical: 10, paddingHorizontal: 16, borderBottomWidth: 2, borderBottomColor: "transparent" },
  tabBtnActive: { borderBottomColor: Colors.maroon },
  tabText: { fontSize: 14, fontFamily: "Montserrat_400Regular", color: Colors.secondaryText },
  tabTextActive: { color: Colors.darkOrange, fontFamily: "Montserrat_400Regular" },
  scroll: { flex: 1 },
  scrollContent: { padding: 16, gap: 12 },
  sectionBlock: {
    backgroundColor: Colors.card,
    borderRadius: 12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: Colors.border,
    marginBottom: 12,
  },
  sectionRow: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    backgroundColor: Colors.beige + "50",
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
    gap: 8,
  },
  sectionInfo: { flex: 1 },
  sectionName: {
    fontSize: 14,
    fontFamily: "PlayfairDisplay_400Regular",
    color: Colors.darkOrange,
    letterSpacing: 0.5,
  },
  sectionSubtitle: {
    fontSize: 11,
    fontFamily: "Montserrat_400Regular",
    color: Colors.secondaryText,
    marginTop: 2,
  },

  // Dark card for main section header
  mainSectionCard: {
    backgroundColor: "#6B4423",
    borderRadius: 12,
    marginBottom: 16,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#5C3A1E",
  },
  mainSectionRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 8,
  },
  mainSectionInfo: { flex: 1 },
  mainSectionName: {
    fontSize: 15,
    fontFamily: "PlayfairDisplay_400Regular",
    color: "#F5EFE7",
    letterSpacing: 1,
  },
  mainSectionSubtitle: {
    fontSize: 11,
    fontFamily: "Montserrat_400Regular",
    color: "#B8A898",
    marginTop: 2,
  },
  mainSectionBtn: {
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    backgroundColor: "rgba(255,255,255,0.08)",
    marginLeft: 4,
  },
  catRow: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    backgroundColor: Colors.beige + "50",
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
    gap: 8,
  },
  catInfo: { flex: 1 },
  catName: {
    fontSize: 14,
    fontFamily: "PlayfairDisplay_400Regular",
    color: Colors.darkOrange,
    letterSpacing: 0.5,
  },
  dishRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 9,
    paddingHorizontal: 10,
    borderTopWidth: 1,
    borderTopColor: Colors.border + "40",
    gap: 8,
  },
  dishInfo: { flex: 1, gap: 2 },
  dishNameRow: { flexDirection: "row", alignItems: "center", gap: 4 },
  dishGlutenFreeIcon: { width: 12, height: 12, tintColor: Colors.glutenBeige },
  dishName: { fontSize: 13, fontFamily: "Montserrat_400Regular", color: Colors.warmBrown, flex: 1 },
  dishSubtitle: { fontSize: 11, fontFamily: "Montserrat_400Regular", color: Colors.secondaryText, marginTop: 1 },
  dishPrice: { fontSize: 12, fontFamily: "Montserrat_400Regular", color: Colors.secondaryText },
  winePriceRow: { flexDirection: "row", gap: 8, flexWrap: "wrap" },
  actions: { flexDirection: "row", gap: 4 },
  actionBtn: { width: 30, height: 30, alignItems: "center", justifyContent: "center" },
  dragHandle: { width: 32, height: 32, alignItems: "center", justifyContent: "center" },
  addDishBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    padding: 10,
    paddingLeft: 14,
    borderTopWidth: 1,
    borderTopColor: Colors.border + "40",
  },
  addDishText: { fontSize: 13, fontFamily: "Montserrat_400Regular", color: Colors.green },
  addCatBtn: { flexDirection: "row", alignItems: "center", gap: 6, padding: 10, paddingLeft: 14 },
  addCatText: { fontSize: 13, fontFamily: "Montserrat_400Regular", color: Colors.secondaryText },
  addSectionBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    justifyContent: "center",
    padding: 16,
    backgroundColor: Colors.card,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: Colors.border,
    borderStyle: "dashed",
    marginBottom: 12,
  },
  addSectionText: { fontSize: 14, fontFamily: "Montserrat_400Regular", color: Colors.green },
  emptyState: { alignItems: "center", paddingVertical: 40 },
  emptyText: { fontSize: 14, fontFamily: "Montserrat_400Regular", color: Colors.secondaryText },
  allergenInfoBox: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    backgroundColor: Colors.beige + "80",
    borderRadius: 10,
    padding: 12,
    marginBottom: 4,
  },
  allergenInfoText: { flex: 1, fontSize: 13, fontFamily: "Montserrat_400Regular", color: Colors.secondaryText, lineHeight: 18 },
  allergenRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.card,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: Colors.border,
    gap: 8,
  },
  allergenInfo: { flex: 1 },
  allergenName: { fontSize: 14, fontFamily: "Montserrat_400Regular", color: Colors.warmBrown },
});

export const formStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.cream },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  title: { fontSize: 18, fontFamily: "PlayfairDisplay_400Regular", color: Colors.darkOrange },
  closeBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.beige,
    alignItems: "center",
    justifyContent: "center",
  },
  scrollContent: { padding: 12, gap: 0, paddingBottom: 16 },
  field: { marginBottom: 10 },
  label: {
    fontSize: 11,
    fontFamily: "Montserrat_400Regular",
    color: Colors.secondaryText,
    letterSpacing: 0.5,
    textTransform: "uppercase",
    marginBottom: 5,
  },
  input: {
    borderWidth: 1.5,
    borderColor: Colors.border,
    borderRadius: 10,
    padding: 11,
    fontSize: 16,
    fontFamily: "Montserrat_400Regular",
    color: Colors.warmBrown,
    backgroundColor: Colors.card,
  },
  inputMulti: { minHeight: 60, textAlignVertical: "top" },
  switchRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  switchLabel: { fontSize: 15, fontFamily: "Montserrat_400Regular", color: Colors.warmBrown },
  switchLabelDisabled: { color: Colors.secondaryText },
  allergenGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  allergenChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: Colors.border,
    backgroundColor: Colors.card,
  },
  allergenChipActive: { borderColor: Colors.green, backgroundColor: Colors.greenLight },
  allergenChipDisabled: { opacity: 0.45 },
  allergenChipText: { fontSize: 12, fontFamily: "Montserrat_400Regular", color: Colors.secondaryText },
  allergenChipTextActive: { color: Colors.green },
  allergenChipTextDisabled: { color: Colors.secondaryText },
  footer: {
    flexDirection: "row",
    padding: 16,
    gap: 12,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
    backgroundColor: Colors.card,
  },
  cancelBtn: {
    flex: 1,
    padding: 14,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: Colors.border,
    alignItems: "center",
  },
  cancelText: { fontSize: 15, fontFamily: "Montserrat_400Regular", color: Colors.secondaryText },
  saveBtn: { flex: 2, padding: 14, borderRadius: 10, backgroundColor: Colors.maroon, alignItems: "center" },
  saveBtnDisabled: { opacity: 0.7 },
  saveText: { fontSize: 15, fontFamily: "Montserrat_400Regular", color: "#fff" },
  positionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    minHeight: 48,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: Colors.border,
    backgroundColor: Colors.card,
    marginBottom: 8,
  },
  positionRowActive: {
    borderColor: Colors.maroon,
    backgroundColor: "#F9F1F2",
  },
  positionLabel: {
    fontSize: 14,
    fontFamily: "Montserrat_400Regular",
    color: Colors.secondaryText,
    flex: 1,
  },
  positionLabelActive: {
    color: Colors.darkOrange,
    fontFamily: "Montserrat_400Regular",
  },
});
